---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rake $COMMAND
rvm: 2.2.3
env:
  - COMMAND=lint
  - COMMAND=metadata
  - COMMAND=spec PUPPET_VERSION=4.10.6
  - COMMAND=spec PUPPET_VERSION=4.9.4
  - COMMAND=spec PUPPET_VERSION=4.8.2
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.10.6 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.10.6 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-10-amd64 PUPPET_INSTALL_VERSION=1.10.6 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.10.6 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.9.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.9.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-10-amd64 PUPPET_INSTALL_VERSION=1.9.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.9.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-6-x64 PUPPET_INSTALL_VERSION=1.8.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=centos-7-x64 PUPPET_INSTALL_VERSION=1.8.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=debian-10-amd64 PUPPET_INSTALL_VERSION=1.8.3 PUPPET_INSTALL_TYPE=agent
  - COMMAND=beaker BEAKER_set=ubuntu-server-1404-x64 PUPPET_INSTALL_VERSION=1.8.3 PUPPET_INSTALL_TYPE=agent
